/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-12-09 17:48:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hometownCviews;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>memberJoin</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/signin.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".modal-sheet .modal-dialog {\r\n");
      out.write("	width: 380px;\r\n");
      out.write("	transition: bottom .75s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-sheet .modal-footer {\r\n");
      out.write("	padding-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hr {\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	background-color: #81DAF5\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("	font-size: 1.125rem;\r\n");
      out.write("	text-anchor: middle;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.bd-placeholder-img-lg {\r\n");
      out.write("		font-size: 3.5rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-divider {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 3rem;\r\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("	border-width: 1px 0;\r\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\r\n");
      out.write("		rgba(0, 0, 0, .15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-vr {\r\n");
      out.write("	flex-shrink: 0;\r\n");
      out.write("	width: 1.5rem;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi {\r\n");
      out.write("	vertical-align: -.125em;\r\n");
      out.write("	fill: currentColor;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	height: 2.75rem;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller .nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	padding-bottom: 1rem;\r\n");
      out.write("	margin-top: -1px;\r\n");
      out.write("	overflow-x: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	-webkit-overflow-scrolling: touch;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-bd-primary { -\r\n");
      out.write("	-bd-violet-bg: #712cf9; -\r\n");
      out.write("	-bd-violet-rgb: 112.520718, 44.062154, 249.437846; -\r\n");
      out.write("	-bs-btn-font-weight: 600; -\r\n");
      out.write("	-bs-btn-color: var(- -bs-white); -\r\n");
      out.write("	-bs-btn-bg: var(- -bd-violet-bg); -\r\n");
      out.write("	-bs-btn-border-color: var(- -bd-violet-bg); -\r\n");
      out.write("	-bs-btn-hover-color: var(- -bs-white); -\r\n");
      out.write("	-bs-btn-hover-bg: #6528e0; -\r\n");
      out.write("	-bs-btn-hover-border-color: #6528e0; -\r\n");
      out.write("	-bs-btn-focus-shadow-rgb: var(- -bd-violet-rgb); -\r\n");
      out.write("	-bs-btn-active-color: var(- -bs-btn-hover-color); -\r\n");
      out.write("	-bs-btn-active-bg: #5a23c8; -\r\n");
      out.write("	-bs-btn-active-border-color: #5a23c8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-mode-toggle {\r\n");
      out.write("	z-index: 1500;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("	<form class=\"form-signin\" action=\"memberJoinProc.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("		<img class=\"mb-4\"\r\n");
      out.write("			src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/hometownIcon.jpg\"\r\n");
      out.write("			alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("\r\n");
      out.write("		<h2>Create account</h2>\r\n");
      out.write("		<p class=\"lead\">Please create an account to use the HT COMMUNITY.</p>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"text-left\">\r\n");
      out.write("				<label for=\"id\" class=\"form-label\">Id</label>\r\n");
      out.write("				<!-- 				<div class=\"input-group mb-3\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"id\" name=\"id\"\r\n");
      out.write("						placeholder=\"\" value=\"\" required>\r\n");
      out.write("					<div class=\"invalid-feedback\">아이디를 입력하세요!</div>\r\n");
      out.write("\r\n");
      out.write("					<input class=\"btn btn-primary\" type=\"button\" id=\"checkId\"\r\n");
      out.write("						value=\"ID CHECK\" />\r\n");
      out.write("\r\n");
      out.write("				</div> -->\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"id\" name=\"id\"\r\n");
      out.write("					placeholder=\"\" value=\"\" required>\r\n");
      out.write("				<div class=\"invalid-feedback\">아이디를 입력하세요!</div>\r\n");
      out.write("\r\n");
      out.write("				<label for=\"username\" class=\"form-label\">Username</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"username\" name=\"username\"\r\n");
      out.write("					placeholder=\"Username\" required>\r\n");
      out.write("				<div class=\"invalid-feedback\">이름을 입력하세요!</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<label for=\"password\" class=\"form-label\">Password</label> <input\r\n");
      out.write("					style=\"margin-bottom: 0px\" type=\"password\" class=\"form-control\"\r\n");
      out.write("					id=\"password\" name=\"password\">\r\n");
      out.write("				<div class=\"invalid-feedback\">비밀번호를 입력하세요!</div>\r\n");
      out.write("\r\n");
      out.write("				<label for=\"address\" class=\"form-label\">Address</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"address\" name=\"address\"\r\n");
      out.write("					placeholder=\"서울특별시 강동구 성내동\" required>\r\n");
      out.write("				<div class=\"invalid-feedback\">주소를 입력해주세요!</div>\r\n");
      out.write("\r\n");
      out.write("				<label for=\"phone\" class=\"form-label\">Phone</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\"\r\n");
      out.write("					placeholder=\"01012345678\" required>\r\n");
      out.write("				<div class=\"invalid-feedback\">전화번호를 입력해주세요!</div>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">Join!</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- <form action=\"memberJoinProc.do\" method=\"post\">\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("	<tr height=\"50\" align=\"center\">\r\n");
      out.write("		<td width=\"150\">아이디</td>\r\n");
      out.write("		<td width=\"250\"><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr height=\"50\" align=\"center\">\r\n");
      out.write("		<td width=\"150\">이름</td>\r\n");
      out.write("		<td width=\"250\"><input type=\"text\" name=\"username\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr height=\"50\" align=\"center\">\r\n");
      out.write("		<td width=\"150\">비밀번호</td>\r\n");
      out.write("		<td width=\"250\"><input type=\"text\" name=\"password\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		<tr height=\"50\" align=\"center\">\r\n");
      out.write("		<td width=\"150\">전화번호</td>\r\n");
      out.write("		<td width=\"250\"><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr height=\"50\" align=\"center\">\r\n");
      out.write("		<td colspan=\"2\">\r\n");
      out.write("			<input type=\"submit\" value=\"등록\"/>\r\n");
      out.write("			<input type=\"reset\" value=\"초기화\"/>	\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
